CC1 = g++
CFLAGS1 = -g -O0
CC2 = g++
CFLAGS2 = -g -O3
all:
	$(CC1) $(CFLAGS1) ./source_code/BubbleSort.cpp  -o BubbleSort1
	$(CC2) $(CFLAGS2) ./source_code/BubbleSort.cpp  -o BubbleSort2
clean:
	rm -f *.o fibon*
