[
    [ "dr_annotation.h", "dr__annotation_8h.html", {% include_relative dr__annotation_8h.js %} ],
    [ "dr_api.h", "dr__api_8h.html", {% include_relative dr__api_8h.js %} ],
    [ "dr_app.h", "dr__app_8h.html", {% include_relative dr__app_8h.js %} ],
    [ "dr_config.h", "dr__config_8h.html", {% include_relative dr__config_8h.js %} ],
    [ "dr_defines.h", "dr__defines_8h.html", {% include_relative dr__defines_8h.js %} ],
    [ "dr_events.h", "dr__events_8h.html", {% include_relative dr__events_8h.js %} ],
    [ "dr_frontend.h", "dr__frontend_8h.html", {% include_relative dr__frontend_8h.js %} ],
    [ "dr_inject.h", "dr__inject_8h.html", {% include_relative dr__inject_8h.js %} ],
    [ "dr_ir_decode.h", "dr__ir__decode_8h.html", {% include_relative dr__ir__decode_8h.js %} ],
    [ "dr_ir_disassemble.h", "dr__ir__disassemble_8h.html", {% include_relative dr__ir__disassemble_8h.js %} ],
    [ "dr_ir_encode.h", "dr__ir__encode_8h.html", {% include_relative dr__ir__encode_8h.js %} ],
    [ "dr_ir_instr.h", "dr__ir__instr_8h.html", {% include_relative dr__ir__instr_8h.js %} ],
    [ "dr_ir_instr_inline.h", "dr__ir__instr__inline_8h.html", null ],
    [ "dr_ir_instrlist.h", "dr__ir__instrlist_8h.html", {% include_relative dr__ir__instrlist_8h.js %} ],
    [ "dr_ir_macros.h", "dr__ir__macros_8h.html", {% include_relative dr__ir__macros_8h.js %} ],
    [ "dr_ir_macros_aarch64.h", "dr__ir__macros__aarch64_8h.html", {% include_relative dr__ir__macros__aarch64_8h.js %} ],
    [ "dr_ir_macros_arm.h", "dr__ir__macros__arm_8h.html", {% include_relative dr__ir__macros__arm_8h.js %} ],
    [ "dr_ir_macros_x86.h", "dr__ir__macros__x86_8h.html", {% include_relative dr__ir__macros__x86_8h.js %} ],
    [ "dr_ir_opcodes_aarch64.h", "dr__ir__opcodes__aarch64_8h.html", {% include_relative dr__ir__opcodes__aarch64_8h.js %} ],
    [ "dr_ir_opcodes_arm.h", "dr__ir__opcodes__arm_8h.html", {% include_relative dr__ir__opcodes__arm_8h.js %} ],
    [ "dr_ir_opcodes_x86.h", "dr__ir__opcodes__x86_8h.html", {% include_relative dr__ir__opcodes__x86_8h.js %} ],
    [ "dr_ir_opnd.h", "dr__ir__opnd_8h.html", {% include_relative dr__ir__opnd_8h.js %} ],
    [ "dr_ir_utils.h", "dr__ir__utils_8h.html", {% include_relative dr__ir__utils_8h.js %} ],
    [ "dr_modules.h", "dr__modules_8h.html", {% include_relative dr__modules_8h.js %} ],
    [ "dr_os_utils.h", "dr__os__utils_8h.html", {% include_relative dr__os__utils_8h.js %} ],
    [ "dr_proc.h", "dr__proc_8h.html", {% include_relative dr__proc_8h.js %} ],
    [ "dr_tools.h", "dr__tools_8h.html", {% include_relative dr__tools_8h.js %} ],
    [ "dr_tracedump.h", "dr__tracedump_8h.html", {% include_relative dr__tracedump_8h.js %} ]
],